services:
  gateway:
    build:
      context: gw-build
      args:
        IGNITION_VERSION: 8.1.46
    hostname: gateway
    ports:
      - 9088:8088
    volumes:
      - gateway-data:/usr/local/bin/ignition/data
      - ./gw-init/gateway.gwbk:/restore.gwbk
      - ./gw-init/gateway-uuid.txt:/usr/local/bin/ignition/data/.uuid
      - ./gw-init/gateway-metro-keystore:/usr/local/bin/ignition/data/local/metro-keystore
    networks:
      - gateway-network
    environment:
      - IGNITION_EDITION=standard
      - GATEWAY_ADMIN_PASSWORD=katlego
      - ACCEPT_IGNITION_EULA=Y
    command: >
      -n gateway
      -m 2048
      -r /restore.gwbk
  db:
    image: mariadb:10.10.2
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      gateway-network:
        aliases:
          - main-db
    environment:
      - MARIADB_ROOT_PASSWORD=ignition
      - MARIADB_DATABASE=ignition
      - MARIADB_USER=ignition
      - MARIADB_PASSWORD=ignition

networks:
  gateway-network:
volumes:
  gateway-data:
  db-data: